goovn/ovnnbimp_test.go
OVS sandbox NB DB socket name changed from ovn-nb.sock to nb1.ovsdb,
which causes existing test initialization failing. This patch makes
it smarter to read from $OVN_NB_DB env.
=> Fix test init.

.travis.yml, .travis/test.sh
Setup OVN-NB ovsdb and cleanup automatically with test.sh, and add
travis.yml to run test.sh.
=> Add support for travis test automation.

examples/main.go, goovn/apis.go, goovn/ovndb.go, goovn/ovnnb.go, goovn/ovnnbimp.go, goovn/ovnnbimp_test.go
Support Ovn Load Balancer operations in go-ovn
=> Support Ovn Load Balancer operations

goovn/apis.go, goovn/ovndb.go, goovn/ovnnb.go, goovn/ovnnbimp.go, goovn/ovnnbimp_test.go, goovn/uuid.go
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>
=> return errors when it happened

.travis.yml, .travis/test.sh
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>
=> fix tests and add go 1.12.x to travis testing

README.md
**Punctuation changes:**
1. convertion ==> conversion
2. north-bound  ==> northbound
3. those overhead ==> the overhead
**Other changes:** 
1. Fixed non-linked hyperlink.
2. Added period at end of sentence.
3. Edited "those overhead" to "the overhead".
=> Fixed a few punctuation errors

logical_router.go, logical_router_test.go
Find it can't show any LoadBlancer , ports, staticRouter information in LRGet ,try to add it.
=> show lb , ports ,sr in LRGet

acl_test.go, client.go, dhcp_options_test.go, logical_router.go, logical_router_static_route.go, logical_router_test.go, logical_switch_load_balancer_test.go, nat.go, qos_test.go
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>
=> fix goreportcard issues

acl.go, address_set.go, address_set_test.go, apis.go, client.go, config.go, dhcp_options.go, examples/main.go, gateway_chassis.go, load_balancer.go, logical_router.go, logical_router_port.go, logical_router_static_route.go, logical_router_static_route_test.go, logical_switch.go, logical_switch_port.go, nat.go, ovnnbimp.go, port_group.go, qos.go
some fixes to makes goreportcard happy
=> goreportcard fixes

acl.go, acl_test.go, apis.go, client.go, examples/main.go, meter.go, meter_test.go, ovnnbimp.go
Fixd: ACL List miss filed , it should have meter before fix it .
Add: meter add , delete , list  and a meter bands List method.
Signed-off-by: JackyCZJ <chenzj@esixnetwork.net>
#62
=> ACL miss filed , Meter Option.

client.go, config.go, ovnimp.go, ovnnotify.go
This patch implements auto-reconnection, and it can be enabled by
setting Config.Reconnect to true when calling NewClient().
Signed-off-by: Han Zhou <hzhou8@ebay.com>
=> Support automatically reconnect when disconnected from server.

client.go, logical_router_static_route.go, logical_router_static_route_test.go
add new API to delete route by prefix, nexthop and policy.
nexthop and policy are optional.
=> delete route by additional parameters

client.go, logical_router_static_route.go, logical_router_static_route_test.go
allow client to delete static route by uuid
=> delete static route by uuid

.travis/test.sh
Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>
addresses issue: https://github.com/eBay/go-ovn/issues/107
=> updated the testing to use a more updated ovs/ovn environment

chassis_private.go, chassis_private_test.go, client.go, common.go
- ChassisPrivateDel() - Delete row in chassis_private table
with given chassis name
- ChassisPrivateList() - List all chassis rows in chassis_private table
Signed-off-by: Pardhakeswar Pacha <ppacha@nvidia.com>
=> Add support for OVN SB-DB Chassis_Private table

client.go
Signed-off-by: Pardhakeswar Pacha <ppacha@nvidia.com>
=> Add GetSchema() API

client.go
Signed-off-by: Pardhakeswar Pacha <ppacha@nvidia.com>
=> Check tables in SBTablesOrder & NBTablesOrder with current ovn-db schema

load_balancer.go, load_balancer_test.go
Co-authored by : Sayandeep Sen sayandes@in.ibm.com
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
=> Externalize fields in load balancer

client.go, load_balancer.go, load_balancer_test.go
This PR adds functionality LBList() for listing all Load Balancers 
Co-authored by : Sayandeep Sen sayandes@in.ibm.com
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
=> List all load balancers

client.go, common.go, logical_router.go, logical_router_policy.go, logical_router_policy_test.go
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
=> Add Logical Route Policy table

client.go, ovnimp.go, ovnimp_test.go
@hzhou8 @anfredette FYI, this is a replacement for #135. Reworked per suggestions (see review comments). LSP type setting not in scope, will submit a separate PR for that.
=> set/delete key-values for OvsMap columns
