eBay/go-ovn

- vendor/github.com/socketplane/libovsdb/client.go
- vendor/github.com/socketplane/libovsdb/set.go
Commit 340f8e3d overwritten the patches we added for libovsdb. Those
patches are required for goovn to work properly. The tests were broken.
This patch adds those changes back. The fixes overwritten are:
6800727 Json marshal should be array of zero size, not null
0d9b1b7 NTWK-2550: fix libovndb cache update problem
> Adding back the fixes to libovsdb.

- load_balancer.go
- ovnnbimp.go
- ovnnbimp_test.go
Creating LB will add load_balancer entries in all logical switches in ovn
to ensure routing is taken care within all the lswitches for the particular vip.
However, delete lb doesnt iterate to all the lswitches and hence lb
delete fails saying multiple references found accross multiple switches.
Hence, we need to clean up lbuuid from all lswitches to avoid this error.
Newer versions of OVN do handle this condition by default where delete LB
will delete all the references too. So, adding this support for environments
using older ovn versions
> Fix LB delete operation for all ovn versions:

- acl_test.go
- apis.go
- dhcp_options.go
- dhcp_options_test.go
- examples/main.go
- logical_router.go
- logical_router_port_test.go
- logical_router_test.go
- logical_switch.go
- logical_switch_load_balancer_test.go
- logical_switch_port.go
- ovnnb.go
- qos_test.go
* change method names to looks like ovn-nbctl
* fix logical switch list to use cache, cleanup unused method from
dhcp_options.
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>
> align method names with ovn-nbctl

- ovn_connect_test.go
Current connect string to libovsdb always passes tcp.
Hence, ssl will not work if client wants to use ssl.
This commit fixes the same.
> Fix connect string for ssl

- ovn_connect_test.go
Since we switched to universal connect in libovsdb,
https://github.com/eBay/libovsdb/commit/df4f42ff0dbc7ccda2df8ca093f129ad686d2c51;
we need to set certs for ssl from client to leverage ssl settings.
This patch adds this feature.
> Add tls settings from client:

- common.go
- ovnnbimp.go
When a logical router update (https://github.com/eBay/go-ovn/blob/84e1e53ffe4fbd63d1b1b4ec3124fae5fb9827cb/ovnnbimp.go#L205) is processed, the `ports` field is considered. If the logical router ports were not processed before, the call to `rowToLogicalRouterPort` (https://github.com/eBay/go-ovn/blob/84e1e53ffe4fbd63d1b1b4ec3124fae5fb9827cb/logical_router.go#L154) will crash as the ports are missing from the cache.
This is because the table updates is a `map[string]TableUpdate`, so there is no guarantee on the tables processing order.
> Process table updates in the right order when populating cache

- acl_test.go
- dhcp_options_test.go
- logical_router_load_balancer_test.go
- logical_router_port_test.go
- logical_router_test.go
- nat_test.go
- qos_test.go
Unit tests always work fine on first time. Hence, travis build always passes.
Re-running same tests againts same ovn setup fails as entities that were
created failed to clean up.
Hence, this patch fixes the same by handling all such cases.
> Fix Unit tests:

- .travis/test.sh
due to ovs/ovn split, ovs master doesn't work with go-ovn test,
use branch-2.12 instead.
> pull ovs/branch-2.12 to test

- client.go
- logical_switch.go
- logical_switch_test.go
The function accepts switch name, switch port name, router name, router port
name, router port mac, network and etc, then does following:
1. create router port
2. create switch port
3. add router port to router
4. add switch port to switch
so that the switch will be connected to router.
> Add function to link switch to router

- go.mod
- go.sum
- logical_switch_test.go
commit f356370 added tests for linking lr to ls.
However, it failed to cleanup the LR and LS. Re-running the test
failed. Hence, this patch cleans up entities that failed to cleanup.
> LS Unit tests fix

- apis.go
- chassis.go
- chassis_encap_test.go
- client.go
- encap.go
- ovnimp.go
Current code only supports one encap for a chassis.
Hence, add support for adding one or many encaps for the chassis.
e.g. ovn-sbctl chassis-add ch1 stt,geneve,vxlan 1.2.3.5
> SB db chassis and encaps enhancements:

- .travis/test.sh
- acl_test.go
- address_set_test.go
- chassis_encap_test.go
- chassis_test.go
- client.go
- config.go
- dhcp_options_test.go
- examples/main.go
- load_balancer_test.go
- logical_router_load_balancer_test.go
- logical_router_port_test.go
- logical_router_static_route_test.go
- logical_router_test.go
- logical_switch_load_balancer_test.go
- logical_switch_test.go
- meter_test.go
- nat_test.go
- ovnimp.go
- qos_test.go
- test_common.go
1. Each UT should use its own client
2. Handle client interface to default to nb db if no db
is passed to ensure old client interface is backward
compatible.
3. Fix CI to run all UTs accordingly.
> Refactor client, api and UTs:

- client.go
- config.go
- test_common.go
Since new clients can now specify where they want to connect to,
either nb db or sb db, make db identifier as exportable so that
when used in other packages, it can be available to use as is.
> Make db as exportable

- acl_test.go
- address_set_test.go
- chassis_encap_test.go
- chassis_test.go
- client.go
- common.go
- load_balancer_test.go
- logical_router_load_balancer_test.go
- logical_router_port_test.go
- logical_router_static_route_test.go
- logical_router_test.go
- logical_switch_load_balancer_test.go
- logical_switch_test.go
- meter_test.go
- nat_test.go
- qos_test.go
- test_common.go
Since clients specify either nb or sb db, client can re-use the constants
from go-ovn directly.
Hence, renaming dbNB as dbSB to make those identifiers explortable.
> Make DB constants as exportable

- logical_router_static_route.go
- logical_router_static_route_test.go
When listing static routes for a logical router, ensure router exist in ovn.
Current code returns empty static routes list without any error.
Hence, this commit fixes it.
> Fix lr static route client error

- acl.go
- acl_test.go
- chassis_encap_test.go
- encap.go
- logical_router.go
- logical_router_load_balancer_test.go
- logical_router_port.go
- logical_router_port_test.go
- logical_router_static_route_test.go
- logical_router_test.go
- logical_switch.go
- logical_switch_load_balancer_test.go
- logical_switch_port.go
- logical_switch_test.go
- qos.go
- qos_test.go
- test_common.go
e.g when listing logical router ports, return error if router is not
present in ovn.
Similarly fix for rest entities like load balancer list, ls port list,
qos, acl, encaps, etc.
This is already being handled in ovn-nb/sbctl clients in ovn. Hence,
handling the same here.
> Improvise error handling if object does not exist.

- apis.go
- client.go
- examples/main.go
Before:
---
ocmd, _ := ovndbapi.LSAdd("ls1")
ovndbapi.Execute(ocmd)
After:
---
ocmd, _ := ovndbapi.LSAdd("ls1")
ocmd.Execute()
> Fix missing parameters of execution function of OvnCommand

- acl.go
> Fix panic on cacheACL.Fields["meter"] type assertion

- client.go
- logical_switch_port.go
- logical_switch_port_test.go
This pull request adds support for 
1) the LSPGet API in the client's interface. The implementation is already present, but the API was not being exposed.
2) dynamic address configuration for the logical switch port.
3) support for configuration of external ids on the logical switch port.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
> Support for LSPGet API in the client interface as well as configuration of LSP fields

- logical_switch_port.go
- ovnimp.go
- port_group.go
There was a left-over type assertion after changes were made to do a switch for the contained type of the interface. This commit fixes that.
> Remove spurious dynamic address type assertion

- client.go
- common.go
- global_common.go
- logical_switch_port.go
- logical_switch_port_test.go
- nb_global.go
- nb_global_test.go
- sb_global.go
- sb_global_test.go
This commit adds support for creating and deleting NB/SB rows via the go-api as also the ability to set options on the rows. In reality the add/delete rows is only used for unit-testing since ovn-northd is the one that creates the rows during start up in the NB_Global table.
There was also a bug in the way the LSP SetOptions and SetExternalIds api worked. Updating entries in these maps would fail since instead of calling an `opUpdate` on the entire row, these APIs were trying to mutate options/external-ids using individual key-values using `opInsert`. That would have failed unless there is a delete first followed by an insert.
> Add api support for NB/SB Global tables and fix the LSP APIs for options and external ids.

- chassis.go
currently, we try to match twice while matching once is enough
@vtolstov @hzhou8 @noah8713 PTAL. Thanks
> in ChassisGet API iterate to the next chassis after a match

- chassis_test.go
- ovnimp.go
- ovnimp_test.go
the results of the operations specified in the transact method is not
correctly verified. we need to always walk through the operations'
results to check for null error to claim a transaction has succeded.
furthermore, per RFC 7047 section 4.1.3, if all of the operations
succeed, but the results cannot be committed, then "result" will have
one more element than "params", with the additional element being an
<error>. this case was not handled as well.
with the fix in place, errors related to "constraint violation",
"referential integrity violation", "resources exhausted", and
"I/O error" are being caught.
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>
@hzhou8 @noah8713 @vtolstov PTAL
> handle error in operations' result from transact method correctly

- chassis.go
- chassis_test.go
- client.go
we have a need to list all the chassis from the OVN SB. this commit
adds support for it and also updates the test for the same
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>
@hzhou8 @vtolstov @noah8713 PTAL
> add support for chassisList API

- .travis/test.sh
the current invocation of `pkill ovsdb-server` kills all instances of
ovsdb-server on the build machine. my build machine uses OVS on the
host for switching and it kills the host's ovsdb-server instance as well
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>
@hzhou8 @noah8713 @vtolstov PTAL
> use 'ovs-appctl exit' instead of 'pkill ovsdb-server'

- client.go
- client_test.go
- common.go
- config.go
- ovnimp.go
- test_common.go
this commit adds a new field to Config struct called TableCols which
is of type map[string][]string (maps table names to columns). with this
user can specify what tables in NB or in SB they would like to Monitor.
in a large scale OVN K8s cluster, the SB DB will be huge with 1000s of
entries in various tables (Logical_Flow, Port_Binding, adn so on),
neither do we want to get the initial data for these tables nor we want
updates for these tables and this commit provides a way to specify the
tables the user is interested in
adding support for specific columns within a table needs some more work
since all of the rowTo<tableName>() functions need to be updated to
reflect missing fields in the Row (since client expressed interest in
only subset of rows)
@noah8713 @hzhou8 @vtolstov PTAL
> Support for monitoring selected tables in OVN NB or SB DB

- acl.go
- address_set.go
- chassis.go
- client_test.go
- common.go
- dhcp_options.go
- encap.go
- load_balancer.go
- logical_router.go
- logical_router_port.go
- logical_router_static_route.go
- logical_switch.go
- logical_switch_port.go
- meter.go
- nat.go
- nb_global.go
- ovnimp.go
- port_group.go
- qos.go
- sb_global.go
Since clients can watch on specific nb/sb tables, client can re-use
those table constants from go-ovn directly.
Hence, using upper case for tables to make those identifiers exportable.
> Make table constants as exportable

- client.go
we weren't stopping the ticker once its job was done in reconnect(),
this commit fixes that issue
@noah8713 @hzhou8 @vtolstov PTAL
> stop the ticker to release associated resources

- acl.go
- address_set.go
- chassis.go
- dhcp_options.go
- encap.go
- logical_router.go
- logical_router_port.go
- logical_router_static_route.go
- logical_switch.go
- logical_switch_port.go
- meter.go
- qos.go
The current implementation of *ListImpl() functions allocate more memory
than that is required. We can just allocate the slice with exact
capacity as we know the number of the logical resources.
Fixes issue (#102)
Signed-off-by: Yun Zhou <yunz@nvidia.com>
> allocate slice with known capacity in *ListImpl() functions

- chassis.go
- port_group.go
chassis' transport_zones and vtep_logical_switches are of type string
port_gruop's ports and acls are of type UUIDs
@hzhou8 @noah8713 @vtolstov PTAL
> fix incorrect column type assumptions in chassis and port_group table

- logical_router_static_route.go
- ovnimp.go
- ovnimp_test.go
This PR fixes following issues:
- fix logical_router_static_route table's column type assumption
the code currently assumes that the policy and output_port columns of
logical_router_static_route table to be of type UUID, however it is
of type string
- GoSet could have not just strings but also set of uuids
the current ConvertGoSetToStringArray() API assumes that the GoSet
consists of only strings but it could also contain set of UUIDs (for
example logical_switch`ports column).
> GoSet could have not just strings but also set of uuids

- client.go
- logical_router_static_route.go
- logical_router_static_route_test.go
- ovnimp.go
The APIs LRSRAdd and LRSRDel were broken when output_port and policy parameters were used. Test case was missing this part. The first patches in the PR fix the bug. The latter patches update the API signature to be more straightforward. Although the API signature is changed, it shouldn't create compatibility problem given that the APIs were broken before this PR.
> Fix LogicalRouterStaticRoute related APIs

- ovnimp.go
The current logic is correct but a little confusing. The flag is initialized
to false, and flips to true if the *first* column matches which is unnecessary.
Signed-off-by: Han Zhou <hzhou8@ebay.com>
> Refactor getRowUUIDs()

- logical_router.go
- port_group.go
To be consistent and make the code more neat instead of typing
same table name with uuid column.
Signed-off-by: Aliasgar Ginwala <aginwala@ebay.com>
> Refactor rowToLogicalRouter() and RowToPortGroup()

- apis.go
Fixes the OVNSignal interface to let its all methods to be public. This
is necessary from consumer side to define OVNSignal implementation.
> ovnsignal: expose all methods as public

- ovnimp.go
My bad, the signalCB now should use the capitalized function name. This
is a build error.
> ovnimpl: use the updated callback name

- logical_router.go
- test_common.go
If SignalCB is registered, the populateCache() function will always
call the rowToXXX() functions of each module. In rowToLogicalRouter()
it will crash at some point in most cases because the implementation
was trying to resolve the rows being referenced by the LR row, e.g.
the LB rows or LRP rows, which may not have been populated to the
cache yet.
In fact, the API was always treating the rows being referenced as
simply uuid strings rather than any specific fields, so there is
no point to resolve the rows. So this patch fixes it by following
the existed pattern, such as rowToLogicalSwitch, simply stores
the uuids of the rows being referenced.
Without this fix, the added signal handler in test_common.go would
cause test failures such as:
=== RUN   TestLRLoadBalancer
[unix nb1.ovsdb] …
> Fix panic of rowToLogicalRouter() when SignalCB is registered.

- client.go
- load_balancer.go
- load_balancer_test.go
Since OVN version 20.06.0, load balancers have a new column
'selection_fields' that allows to define a set of packet
headers to use while selecting the backend, so that session
affinity can be implemented.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
Fixes: https://github.com/eBay/go-ovn/issues/112
> add selection_fields to the load balancer 

- .travis/test.sh
- nb_global_test.go
- sb_global_test.go
This PR adds a build tag `travis` for the files `sb_global_test.go` and `nb_global_test.go`. The tests `TestSBGlobalAPI` and `TestNBGlobalAPI`run successfully only when the `.travis\test.sh` script is invoked which is long running and is needed as part of travis CI run.
For all other tests, the regular go testing command 'go test' should be sufficent and faster. So now with this PR, one can execute `OVN_NB_DB=unix:ovnnb_db.sock OVN_SB_DB=unix:ovnsb_db.sock OVS_RUNDIR=/var/run/ovn go test` which will skip the TestSBGlobalAPI` and `TestNBGlobalAPI` tests but run everything else. The TestSBGlobalAPI` and `TestNBGlobalAPI` tests will still continue to be run along with the other tests when the `.travis/test.sh` is executed
Signed-off-by: Vishwanath Jayaraman <vjayaram@redhat.com>
> use build tag to group tests that needs to be mandatorily run as part of travis test script

- client.go
- ovnimp.go
- port_group.go
- port_group_test.go
ovn-kubernetes needs the ability to add ACLs to port groups, but the current ACL APIs only support logical switches, and there are no port group APIs. This PR adds port group API support and tests.
> Port group API support

- acl.go
- acl_test.go
See https://github.com/eBay/go-ovn/issues/124 for details
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Fix issue #124: acl add/delete code isn't handling external_ids correctly

- acl.go
- acl_test.go
- client.go
- port_group.go
- port_group_test.go
- test_common.go
Added support for ACLs on port groups.
- Using ovn-nbctl acl-add/del as a model, an entityType parameter was added to
the API which could be either PORT_GROUP or LOICAL_SWITCH.
- In order to maintain backward compatibility of the existing APIs, a new set
of APIs called ACLAddEntity/ACLDelEntity/ACLListEntity were added.
- Note: both versions of the APIs call the same underlying
implementation functions.
Also made a minor optimization suggested by vtolstov on pr-117.
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Added support for ACLs on port groups.

- client.go
- ovnimp.go
- port_group.go
- port_group_test.go
- PortGroupAddPort() - Add a port to a port group
- PortGroupRemovePort() - Remove a port from a port group
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Extend port group API to support:

- acl_test.go
- client.go
- ovnimp.go
- ovnimp_test.go
- port_group_test.go
ExecuteR() works the same as the existing Execute() function, except that it returns a list of UUIDs -- one for each object created in the call. If no objects are created in the ExecuteR call, or there is an error, nil is returned. Execute() has been updated to call ExecuteR() and ignore the returned UUIDs to avoid duplication of code.
The reason such a command is useful is that in many cases, the user of our API needs the UUID of the object or objects created. In order to get that UUID, an additional call and in some cases code is needed to get the object and then extract the UUID. Since we already have the UUID in the libovsdb.OperationResult returned from transact, it's more efficient to return it from the Execute call.
> Implement a new API called ExecuteR()

- client.go
- logical_switch_port.go
- logical_switch_port_test.go
need this is to allow setting of a desired logical switch port type, e.g., localnet
> add LSP type setter

- acl.go
- acl_test.go
- client.go
- meter_test.go
- test_common.go
- Support setting ACL name in ACLAddEntity()
- Add ACL set support for ACL name, match and logging for an existing ACL
- Use ACL UUID to identify ACL in ACLDelEntity()
Addresses Issues #137 and #138
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Extend ACL API to support changing match critera and logging for an existing ACL

- client.go
- ovnimp.go
- ovnnotify.go
Two fixes here:
- we wipe out the cache when reconnecting (this is because we don't get the "deletion" events from MonitorTables
- we setup the notifier before fetching the db dump and initializing the cache. This avoid missed events in between
> Connect - reconnect cache correctness

- port_group.go
- port_group_test.go
Rather than checking to see if a given port is already in a group, just
always transact. The ovsdb protocol already understands set membership
and will happily allow duplicate adds.
Signed-off-by: Casey Callendrello <cdc@redhat.com>
> PortGroup: make group membership APIs idempotent

- logical_switch_port.go
it is just sufficient to remove the LSP's UUID from the LS's Ports
column, and this in itself will remove the LSP from the table since
LSP can't be present by itself
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>
@hzhou8 @noah8713 PTAL
> no need to destroy LSP row when also removing from LS' ports column

- client.go
- ovnimp.go
The transaction mutex is not necessary, because the rpc2 lib and ovsdb
protocol ensure that a cache/db update is received before the
transaction is complete, and every transaction is serialized.
Signed-off-by: Tim Rozet <trozet@redhat.com>
> Remove transaction mutex
